import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <Header />
                <div className="flex min-h-screen">
                    <Sidebar />
                    <main className="flex-1 bg-[#F4F7FF] pt-14">
                        {children}
                    </main>
                </div>
            </body>
        </html>
    );
}
